// Vercel serverless entry. `_app.mjs` is generated by `npm run build` (see
// package.json build:api) and bundles everything under server/ into one file.
import { createApp } from "./_app.mjs";

const ready = createApp();

export default async function handler(req, res) {
  const { app } = await ready;
  return app(req, res);
}
